QT -= gui

CONFIG += c++11 console
CONFIG -= app_bundle

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS \
           BOOST_ASIO_SEPARATE_COMPILATION

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
        boost/asio/impl/src.cpp \
        main.cpp

DISTFILES += \
    boost/date_time/gregorian_calendar.ipp \
    lib/libboost_coroutine-mgw8-mt-d-x32-1_73.a \
    lib/libboost_coroutine-mgw8-mt-x32-1_73.a \
    lib/libboost_date_time-mgw8-mt-d-x32-1_73.a \
    lib/libboost_date_time-mgw8-mt-x32-1_73.a \
    lib/libboost_regex-mgw8-mt-d-x32-1_73.a \
    lib/libboost_regex-mgw8-mt-x32-1_73.a \
    lib/libboost_serialization-mgw8-mt-d-x32-1_73.a \
    lib/libboost_serialization-mgw8-mt-x32-1_73.a \
    lib/libboost_system-mgw8-mt-d-x32-1_73.a \
    lib/libboost_system-mgw8-mt-x32-1_73.a \
    lib/libboost_thread-mgw8-mt-d-x32-1_73.a \
    lib/libboost_thread-mgw8-mt-x32-1_73.a \ \
    websocketpp/CMakeLists.txt

HEADERS += \
    boost/asio/associated_allocator.hpp \
    boost/asio/associated_executor.hpp \
    boost/asio/async_result.hpp \
    boost/asio/awaitable.hpp \
    boost/asio/basic_datagram_socket.hpp \
    boost/asio/basic_deadline_timer.hpp \
    boost/asio/basic_io_object.hpp \
    boost/asio/basic_raw_socket.hpp \
    boost/asio/basic_seq_packet_socket.hpp \
    boost/asio/basic_serial_port.hpp \
    boost/asio/basic_signal_set.hpp \
    boost/asio/basic_socket.hpp \
    boost/asio/basic_socket_acceptor.hpp \
    boost/asio/basic_socket_iostream.hpp \
    boost/asio/basic_socket_streambuf.hpp \
    boost/asio/basic_stream_socket.hpp \
    boost/asio/basic_streambuf.hpp \
    boost/asio/basic_streambuf_fwd.hpp \
    boost/asio/basic_waitable_timer.hpp \
    boost/asio/bind_executor.hpp \
    boost/asio/buffer.hpp \
    boost/asio/buffered_read_stream.hpp \
    boost/asio/buffered_read_stream_fwd.hpp \
    boost/asio/buffered_stream.hpp \
    boost/asio/buffered_stream_fwd.hpp \
    boost/asio/buffered_write_stream.hpp \
    boost/asio/buffered_write_stream_fwd.hpp \
    boost/asio/buffers_iterator.hpp \
    boost/asio/co_spawn.hpp \
    boost/asio/completion_condition.hpp \
    boost/asio/compose.hpp \
    boost/asio/connect.hpp \
    boost/asio/coroutine.hpp \
    boost/asio/deadline_timer.hpp \
    boost/asio/defer.hpp \
    boost/asio/detached.hpp \
    boost/asio/detail/array.hpp \
    boost/asio/detail/array_fwd.hpp \
    boost/asio/detail/assert.hpp \
    boost/asio/detail/atomic_count.hpp \
    boost/asio/detail/base_from_completion_cond.hpp \
    boost/asio/detail/bind_handler.hpp \
    boost/asio/detail/buffer_resize_guard.hpp \
    boost/asio/detail/buffer_sequence_adapter.hpp \
    boost/asio/detail/buffered_stream_storage.hpp \
    boost/asio/detail/call_stack.hpp \
    boost/asio/detail/chrono.hpp \
    boost/asio/detail/chrono_time_traits.hpp \
    boost/asio/detail/completion_handler.hpp \
    boost/asio/detail/concurrency_hint.hpp \
    boost/asio/detail/conditionally_enabled_event.hpp \
    boost/asio/detail/conditionally_enabled_mutex.hpp \
    boost/asio/detail/config.hpp \
    boost/asio/detail/consuming_buffers.hpp \
    boost/asio/detail/cstddef.hpp \
    boost/asio/detail/cstdint.hpp \
    boost/asio/detail/date_time_fwd.hpp \
    boost/asio/detail/deadline_timer_service.hpp \
    boost/asio/detail/dependent_type.hpp \
    boost/asio/detail/descriptor_ops.hpp \
    boost/asio/detail/descriptor_read_op.hpp \
    boost/asio/detail/descriptor_write_op.hpp \
    boost/asio/detail/dev_poll_reactor.hpp \
    boost/asio/detail/epoll_reactor.hpp \
    boost/asio/detail/event.hpp \
    boost/asio/detail/eventfd_select_interrupter.hpp \
    boost/asio/detail/executor_function.hpp \
    boost/asio/detail/executor_op.hpp \
    boost/asio/detail/fd_set_adapter.hpp \
    boost/asio/detail/fenced_block.hpp \
    boost/asio/detail/functional.hpp \
    boost/asio/detail/future.hpp \
    boost/asio/detail/gcc_arm_fenced_block.hpp \
    boost/asio/detail/gcc_hppa_fenced_block.hpp \
    boost/asio/detail/gcc_sync_fenced_block.hpp \
    boost/asio/detail/gcc_x86_fenced_block.hpp \
    boost/asio/detail/global.hpp \
    boost/asio/detail/handler_alloc_helpers.hpp \
    boost/asio/detail/handler_cont_helpers.hpp \
    boost/asio/detail/handler_invoke_helpers.hpp \
    boost/asio/detail/handler_tracking.hpp \
    boost/asio/detail/handler_type_requirements.hpp \
    boost/asio/detail/handler_work.hpp \
    boost/asio/detail/hash_map.hpp \
    boost/asio/detail/impl/buffer_sequence_adapter.ipp \
    boost/asio/detail/impl/descriptor_ops.ipp \
    boost/asio/detail/impl/dev_poll_reactor.hpp \
    boost/asio/detail/impl/dev_poll_reactor.ipp \
    boost/asio/detail/impl/epoll_reactor.hpp \
    boost/asio/detail/impl/epoll_reactor.ipp \
    boost/asio/detail/impl/eventfd_select_interrupter.ipp \
    boost/asio/detail/impl/handler_tracking.ipp \
    boost/asio/detail/impl/kqueue_reactor.hpp \
    boost/asio/detail/impl/kqueue_reactor.ipp \
    boost/asio/detail/impl/null_event.ipp \
    boost/asio/detail/impl/pipe_select_interrupter.ipp \
    boost/asio/detail/impl/posix_event.ipp \
    boost/asio/detail/impl/posix_mutex.ipp \
    boost/asio/detail/impl/posix_thread.ipp \
    boost/asio/detail/impl/posix_tss_ptr.ipp \
    boost/asio/detail/impl/reactive_descriptor_service.ipp \
    boost/asio/detail/impl/reactive_serial_port_service.ipp \
    boost/asio/detail/impl/reactive_socket_service_base.ipp \
    boost/asio/detail/impl/resolver_service_base.ipp \
    boost/asio/detail/impl/scheduler.ipp \
    boost/asio/detail/impl/select_reactor.hpp \
    boost/asio/detail/impl/select_reactor.ipp \
    boost/asio/detail/impl/service_registry.hpp \
    boost/asio/detail/impl/service_registry.ipp \
    boost/asio/detail/impl/signal_set_service.ipp \
    boost/asio/detail/impl/socket_ops.ipp \
    boost/asio/detail/impl/socket_select_interrupter.ipp \
    boost/asio/detail/impl/strand_executor_service.hpp \
    boost/asio/detail/impl/strand_executor_service.ipp \
    boost/asio/detail/impl/strand_service.hpp \
    boost/asio/detail/impl/strand_service.ipp \
    boost/asio/detail/impl/throw_error.ipp \
    boost/asio/detail/impl/timer_queue_ptime.ipp \
    boost/asio/detail/impl/timer_queue_set.ipp \
    boost/asio/detail/impl/win_event.ipp \
    boost/asio/detail/impl/win_iocp_handle_service.ipp \
    boost/asio/detail/impl/win_iocp_io_context.hpp \
    boost/asio/detail/impl/win_iocp_io_context.ipp \
    boost/asio/detail/impl/win_iocp_serial_port_service.ipp \
    boost/asio/detail/impl/win_iocp_socket_service_base.ipp \
    boost/asio/detail/impl/win_mutex.ipp \
    boost/asio/detail/impl/win_object_handle_service.ipp \
    boost/asio/detail/impl/win_static_mutex.ipp \
    boost/asio/detail/impl/win_thread.ipp \
    boost/asio/detail/impl/win_tss_ptr.ipp \
    boost/asio/detail/impl/winrt_ssocket_service_base.ipp \
    boost/asio/detail/impl/winrt_timer_scheduler.hpp \
    boost/asio/detail/impl/winrt_timer_scheduler.ipp \
    boost/asio/detail/impl/winsock_init.ipp \
    boost/asio/detail/io_control.hpp \
    boost/asio/detail/io_object_executor.hpp \
    boost/asio/detail/io_object_impl.hpp \
    boost/asio/detail/is_buffer_sequence.hpp \
    boost/asio/detail/is_executor.hpp \
    boost/asio/detail/keyword_tss_ptr.hpp \
    boost/asio/detail/kqueue_reactor.hpp \
    boost/asio/detail/limits.hpp \
    boost/asio/detail/local_free_on_block_exit.hpp \
    boost/asio/detail/macos_fenced_block.hpp \
    boost/asio/detail/memory.hpp \
    boost/asio/detail/mutex.hpp \
    boost/asio/detail/non_const_lvalue.hpp \
    boost/asio/detail/noncopyable.hpp \
    boost/asio/detail/null_event.hpp \
    boost/asio/detail/null_fenced_block.hpp \
    boost/asio/detail/null_global.hpp \
    boost/asio/detail/null_mutex.hpp \
    boost/asio/detail/null_reactor.hpp \
    boost/asio/detail/null_signal_blocker.hpp \
    boost/asio/detail/null_socket_service.hpp \
    boost/asio/detail/null_static_mutex.hpp \
    boost/asio/detail/null_thread.hpp \
    boost/asio/detail/null_tss_ptr.hpp \
    boost/asio/detail/object_pool.hpp \
    boost/asio/detail/old_win_sdk_compat.hpp \
    boost/asio/detail/op_queue.hpp \
    boost/asio/detail/operation.hpp \
    boost/asio/detail/pipe_select_interrupter.hpp \
    boost/asio/detail/pop_options.hpp \
    boost/asio/detail/posix_event.hpp \
    boost/asio/detail/posix_fd_set_adapter.hpp \
    boost/asio/detail/posix_global.hpp \
    boost/asio/detail/posix_mutex.hpp \
    boost/asio/detail/posix_signal_blocker.hpp \
    boost/asio/detail/posix_static_mutex.hpp \
    boost/asio/detail/posix_thread.hpp \
    boost/asio/detail/posix_tss_ptr.hpp \
    boost/asio/detail/push_options.hpp \
    boost/asio/detail/reactive_descriptor_service.hpp \
    boost/asio/detail/reactive_null_buffers_op.hpp \
    boost/asio/detail/reactive_serial_port_service.hpp \
    boost/asio/detail/reactive_socket_accept_op.hpp \
    boost/asio/detail/reactive_socket_connect_op.hpp \
    boost/asio/detail/reactive_socket_recv_op.hpp \
    boost/asio/detail/reactive_socket_recvfrom_op.hpp \
    boost/asio/detail/reactive_socket_recvmsg_op.hpp \
    boost/asio/detail/reactive_socket_send_op.hpp \
    boost/asio/detail/reactive_socket_sendto_op.hpp \
    boost/asio/detail/reactive_socket_service.hpp \
    boost/asio/detail/reactive_socket_service_base.hpp \
    boost/asio/detail/reactive_wait_op.hpp \
    boost/asio/detail/reactor.hpp \
    boost/asio/detail/reactor_fwd.hpp \
    boost/asio/detail/reactor_op.hpp \
    boost/asio/detail/reactor_op_queue.hpp \
    boost/asio/detail/recycling_allocator.hpp \
    boost/asio/detail/regex_fwd.hpp \
    boost/asio/detail/resolve_endpoint_op.hpp \
    boost/asio/detail/resolve_op.hpp \
    boost/asio/detail/resolve_query_op.hpp \
    boost/asio/detail/resolver_service.hpp \
    boost/asio/detail/resolver_service_base.hpp \
    boost/asio/detail/scheduler.hpp \
    boost/asio/detail/scheduler_operation.hpp \
    boost/asio/detail/scheduler_thread_info.hpp \
    boost/asio/detail/scoped_lock.hpp \
    boost/asio/detail/scoped_ptr.hpp \
    boost/asio/detail/select_interrupter.hpp \
    boost/asio/detail/select_reactor.hpp \
    boost/asio/detail/service_registry.hpp \
    boost/asio/detail/signal_blocker.hpp \
    boost/asio/detail/signal_handler.hpp \
    boost/asio/detail/signal_init.hpp \
    boost/asio/detail/signal_op.hpp \
    boost/asio/detail/signal_set_service.hpp \
    boost/asio/detail/socket_holder.hpp \
    boost/asio/detail/socket_ops.hpp \
    boost/asio/detail/socket_option.hpp \
    boost/asio/detail/socket_select_interrupter.hpp \
    boost/asio/detail/socket_types.hpp \
    boost/asio/detail/solaris_fenced_block.hpp \
    boost/asio/detail/static_mutex.hpp \
    boost/asio/detail/std_event.hpp \
    boost/asio/detail/std_fenced_block.hpp \
    boost/asio/detail/std_global.hpp \
    boost/asio/detail/std_mutex.hpp \
    boost/asio/detail/std_static_mutex.hpp \
    boost/asio/detail/std_thread.hpp \
    boost/asio/detail/strand_executor_service.hpp \
    boost/asio/detail/strand_service.hpp \
    boost/asio/detail/string_view.hpp \
    boost/asio/detail/thread.hpp \
    boost/asio/detail/thread_context.hpp \
    boost/asio/detail/thread_group.hpp \
    boost/asio/detail/thread_info_base.hpp \
    boost/asio/detail/throw_error.hpp \
    boost/asio/detail/throw_exception.hpp \
    boost/asio/detail/timer_queue.hpp \
    boost/asio/detail/timer_queue_base.hpp \
    boost/asio/detail/timer_queue_ptime.hpp \
    boost/asio/detail/timer_queue_set.hpp \
    boost/asio/detail/timer_scheduler.hpp \
    boost/asio/detail/timer_scheduler_fwd.hpp \
    boost/asio/detail/tss_ptr.hpp \
    boost/asio/detail/type_traits.hpp \
    boost/asio/detail/variadic_templates.hpp \
    boost/asio/detail/wait_handler.hpp \
    boost/asio/detail/wait_op.hpp \
    boost/asio/detail/win_event.hpp \
    boost/asio/detail/win_fd_set_adapter.hpp \
    boost/asio/detail/win_fenced_block.hpp \
    boost/asio/detail/win_global.hpp \
    boost/asio/detail/win_iocp_handle_read_op.hpp \
    boost/asio/detail/win_iocp_handle_service.hpp \
    boost/asio/detail/win_iocp_handle_write_op.hpp \
    boost/asio/detail/win_iocp_io_context.hpp \
    boost/asio/detail/win_iocp_null_buffers_op.hpp \
    boost/asio/detail/win_iocp_operation.hpp \
    boost/asio/detail/win_iocp_overlapped_op.hpp \
    boost/asio/detail/win_iocp_overlapped_ptr.hpp \
    boost/asio/detail/win_iocp_serial_port_service.hpp \
    boost/asio/detail/win_iocp_socket_accept_op.hpp \
    boost/asio/detail/win_iocp_socket_connect_op.hpp \
    boost/asio/detail/win_iocp_socket_recv_op.hpp \
    boost/asio/detail/win_iocp_socket_recvfrom_op.hpp \
    boost/asio/detail/win_iocp_socket_recvmsg_op.hpp \
    boost/asio/detail/win_iocp_socket_send_op.hpp \
    boost/asio/detail/win_iocp_socket_service.hpp \
    boost/asio/detail/win_iocp_socket_service_base.hpp \
    boost/asio/detail/win_iocp_thread_info.hpp \
    boost/asio/detail/win_iocp_wait_op.hpp \
    boost/asio/detail/win_mutex.hpp \
    boost/asio/detail/win_object_handle_service.hpp \
    boost/asio/detail/win_static_mutex.hpp \
    boost/asio/detail/win_thread.hpp \
    boost/asio/detail/win_tss_ptr.hpp \
    boost/asio/detail/winapp_thread.hpp \
    boost/asio/detail/wince_thread.hpp \
    boost/asio/detail/winrt_async_manager.hpp \
    boost/asio/detail/winrt_async_op.hpp \
    boost/asio/detail/winrt_resolve_op.hpp \
    boost/asio/detail/winrt_resolver_service.hpp \
    boost/asio/detail/winrt_socket_connect_op.hpp \
    boost/asio/detail/winrt_socket_recv_op.hpp \
    boost/asio/detail/winrt_socket_send_op.hpp \
    boost/asio/detail/winrt_ssocket_service.hpp \
    boost/asio/detail/winrt_ssocket_service_base.hpp \
    boost/asio/detail/winrt_timer_scheduler.hpp \
    boost/asio/detail/winrt_utils.hpp \
    boost/asio/detail/winsock_init.hpp \
    boost/asio/detail/work_dispatcher.hpp \
    boost/asio/detail/wrapped_handler.hpp \
    boost/asio/dispatch.hpp \
    boost/asio/error.hpp \
    boost/asio/execution_context.hpp \
    boost/asio/executor.hpp \
    boost/asio/executor_work_guard.hpp \
    boost/asio/generic/basic_endpoint.hpp \
    boost/asio/generic/datagram_protocol.hpp \
    boost/asio/generic/detail/endpoint.hpp \
    boost/asio/generic/detail/impl/endpoint.ipp \
    boost/asio/generic/raw_protocol.hpp \
    boost/asio/generic/seq_packet_protocol.hpp \
    boost/asio/generic/stream_protocol.hpp \
    boost/asio/handler_alloc_hook.hpp \
    boost/asio/handler_continuation_hook.hpp \
    boost/asio/handler_invoke_hook.hpp \
    boost/asio/high_resolution_timer.hpp \
    boost/asio/impl/awaitable.hpp \
    boost/asio/impl/buffered_read_stream.hpp \
    boost/asio/impl/buffered_write_stream.hpp \
    boost/asio/impl/co_spawn.hpp \
    boost/asio/impl/compose.hpp \
    boost/asio/impl/connect.hpp \
    boost/asio/impl/defer.hpp \
    boost/asio/impl/detached.hpp \
    boost/asio/impl/dispatch.hpp \
    boost/asio/impl/error.ipp \
    boost/asio/impl/execution_context.hpp \
    boost/asio/impl/execution_context.ipp \
    boost/asio/impl/executor.hpp \
    boost/asio/impl/executor.ipp \
    boost/asio/impl/handler_alloc_hook.ipp \
    boost/asio/impl/io_context.hpp \
    boost/asio/impl/io_context.ipp \
    boost/asio/impl/post.hpp \
    boost/asio/impl/read.hpp \
    boost/asio/impl/read_at.hpp \
    boost/asio/impl/read_until.hpp \
    boost/asio/impl/redirect_error.hpp \
    boost/asio/impl/serial_port_base.hpp \
    boost/asio/impl/serial_port_base.ipp \
    boost/asio/impl/spawn.hpp \
    boost/asio/impl/src.hpp \
    boost/asio/impl/system_context.hpp \
    boost/asio/impl/system_context.ipp \
    boost/asio/impl/system_executor.hpp \
    boost/asio/impl/thread_pool.hpp \
    boost/asio/impl/thread_pool.ipp \
    boost/asio/impl/use_awaitable.hpp \
    boost/asio/impl/use_future.hpp \
    boost/asio/impl/write.hpp \
    boost/asio/impl/write_at.hpp \
    boost/asio/io_context.hpp \
    boost/asio/io_context_strand.hpp \
    boost/asio/io_service.hpp \
    boost/asio/io_service_strand.hpp \
    boost/asio/ip/address.hpp \
    boost/asio/ip/address_v4.hpp \
    boost/asio/ip/address_v4_iterator.hpp \
    boost/asio/ip/address_v4_range.hpp \
    boost/asio/ip/address_v6.hpp \
    boost/asio/ip/address_v6_iterator.hpp \
    boost/asio/ip/address_v6_range.hpp \
    boost/asio/ip/bad_address_cast.hpp \
    boost/asio/ip/basic_endpoint.hpp \
    boost/asio/ip/basic_resolver.hpp \
    boost/asio/ip/basic_resolver_entry.hpp \
    boost/asio/ip/basic_resolver_iterator.hpp \
    boost/asio/ip/basic_resolver_query.hpp \
    boost/asio/ip/basic_resolver_results.hpp \
    boost/asio/ip/detail/endpoint.hpp \
    boost/asio/ip/detail/impl/endpoint.ipp \
    boost/asio/ip/detail/socket_option.hpp \
    boost/asio/ip/host_name.hpp \
    boost/asio/ip/icmp.hpp \
    boost/asio/ip/impl/address.hpp \
    boost/asio/ip/impl/address.ipp \
    boost/asio/ip/impl/address_v4.hpp \
    boost/asio/ip/impl/address_v4.ipp \
    boost/asio/ip/impl/address_v6.hpp \
    boost/asio/ip/impl/address_v6.ipp \
    boost/asio/ip/impl/basic_endpoint.hpp \
    boost/asio/ip/impl/host_name.ipp \
    boost/asio/ip/impl/network_v4.hpp \
    boost/asio/ip/impl/network_v4.ipp \
    boost/asio/ip/impl/network_v6.hpp \
    boost/asio/ip/impl/network_v6.ipp \
    boost/asio/ip/multicast.hpp \
    boost/asio/ip/network_v4.hpp \
    boost/asio/ip/network_v6.hpp \
    boost/asio/ip/resolver_base.hpp \
    boost/asio/ip/resolver_query_base.hpp \
    boost/asio/ip/tcp.hpp \
    boost/asio/ip/udp.hpp \
    boost/asio/ip/unicast.hpp \
    boost/asio/ip/v6_only.hpp \
    boost/asio/is_executor.hpp \
    boost/asio/is_read_buffered.hpp \
    boost/asio/is_write_buffered.hpp \
    boost/asio/local/basic_endpoint.hpp \
    boost/asio/local/connect_pair.hpp \
    boost/asio/local/datagram_protocol.hpp \
    boost/asio/local/detail/endpoint.hpp \
    boost/asio/local/detail/impl/endpoint.ipp \
    boost/asio/local/stream_protocol.hpp \
    boost/asio/packaged_task.hpp \
    boost/asio/placeholders.hpp \
    boost/asio/posix/basic_descriptor.hpp \
    boost/asio/posix/basic_stream_descriptor.hpp \
    boost/asio/posix/descriptor.hpp \
    boost/asio/posix/descriptor_base.hpp \
    boost/asio/posix/stream_descriptor.hpp \
    boost/asio/post.hpp \
    boost/asio/read.hpp \
    boost/asio/read_at.hpp \
    boost/asio/read_until.hpp \
    boost/asio/redirect_error.hpp \
    boost/asio/serial_port.hpp \
    boost/asio/serial_port_base.hpp \
    boost/asio/signal_set.hpp \
    boost/asio/socket_base.hpp \
    boost/asio/spawn.hpp \
    boost/asio/ssl.hpp \
    boost/asio/ssl/context.hpp \
    boost/asio/ssl/context_base.hpp \
    boost/asio/ssl/detail/buffered_handshake_op.hpp \
    boost/asio/ssl/detail/engine.hpp \
    boost/asio/ssl/detail/handshake_op.hpp \
    boost/asio/ssl/detail/impl/engine.ipp \
    boost/asio/ssl/detail/impl/openssl_init.ipp \
    boost/asio/ssl/detail/io.hpp \
    boost/asio/ssl/detail/openssl_init.hpp \
    boost/asio/ssl/detail/openssl_types.hpp \
    boost/asio/ssl/detail/password_callback.hpp \
    boost/asio/ssl/detail/read_op.hpp \
    boost/asio/ssl/detail/shutdown_op.hpp \
    boost/asio/ssl/detail/stream_core.hpp \
    boost/asio/ssl/detail/verify_callback.hpp \
    boost/asio/ssl/detail/write_op.hpp \
    boost/asio/ssl/error.hpp \
    boost/asio/ssl/host_name_verification.hpp \
    boost/asio/ssl/impl/context.hpp \
    boost/asio/ssl/impl/context.ipp \
    boost/asio/ssl/impl/error.ipp \
    boost/asio/ssl/impl/host_name_verification.ipp \
    boost/asio/ssl/impl/rfc2818_verification.ipp \
    boost/asio/ssl/impl/src.hpp \
    boost/asio/ssl/rfc2818_verification.hpp \
    boost/asio/ssl/stream.hpp \
    boost/asio/ssl/stream_base.hpp \
    boost/asio/ssl/verify_context.hpp \
    boost/asio/ssl/verify_mode.hpp \
    boost/asio/steady_timer.hpp \
    boost/asio/strand.hpp \
    boost/asio/streambuf.hpp \
    boost/asio/system_context.hpp \
    boost/asio/system_executor.hpp \
    boost/asio/system_timer.hpp \
    boost/asio/this_coro.hpp \
    boost/asio/thread_pool.hpp \
    boost/asio/time_traits.hpp \
    boost/asio/ts/buffer.hpp \
    boost/asio/ts/executor.hpp \
    boost/asio/ts/internet.hpp \
    boost/asio/ts/io_context.hpp \
    boost/asio/ts/net.hpp \
    boost/asio/ts/netfwd.hpp \
    boost/asio/ts/socket.hpp \
    boost/asio/ts/timer.hpp \
    boost/asio/unyield.hpp \
    boost/asio/use_awaitable.hpp \
    boost/asio/use_future.hpp \
    boost/asio/uses_executor.hpp \
    boost/asio/version.hpp \
    boost/asio/wait_traits.hpp \
    boost/asio/windows/basic_object_handle.hpp \
    boost/asio/windows/basic_overlapped_handle.hpp \
    boost/asio/windows/basic_random_access_handle.hpp \
    boost/asio/windows/basic_stream_handle.hpp \
    boost/asio/windows/object_handle.hpp \
    boost/asio/windows/overlapped_handle.hpp \
    boost/asio/windows/overlapped_ptr.hpp \
    boost/asio/windows/random_access_handle.hpp \
    boost/asio/windows/stream_handle.hpp \
    boost/asio/write.hpp \
    boost/asio/write_at.hpp \
    boost/asio/yield.hpp \
    boost/assert/source_location.hpp \
    boost/config/abi/borland_prefix.hpp \
    boost/config/abi/borland_suffix.hpp \
    boost/config/abi/msvc_prefix.hpp \
    boost/config/abi/msvc_suffix.hpp \
    boost/config/abi_prefix.hpp \
    boost/config/abi_suffix.hpp \
    boost/config/auto_link.hpp \
    boost/config/compiler/borland.hpp \
    boost/config/compiler/clang.hpp \
    boost/config/compiler/codegear.hpp \
    boost/config/compiler/comeau.hpp \
    boost/config/compiler/common_edg.hpp \
    boost/config/compiler/compaq_cxx.hpp \
    boost/config/compiler/cray.hpp \
    boost/config/compiler/diab.hpp \
    boost/config/compiler/digitalmars.hpp \
    boost/config/compiler/gcc.hpp \
    boost/config/compiler/gcc_xml.hpp \
    boost/config/compiler/greenhills.hpp \
    boost/config/compiler/hp_acc.hpp \
    boost/config/compiler/intel.hpp \
    boost/config/compiler/kai.hpp \
    boost/config/compiler/metrowerks.hpp \
    boost/config/compiler/mpw.hpp \
    boost/config/compiler/nvcc.hpp \
    boost/config/compiler/pathscale.hpp \
    boost/config/compiler/pgi.hpp \
    boost/config/compiler/sgi_mipspro.hpp \
    boost/config/compiler/sunpro_cc.hpp \
    boost/config/compiler/vacpp.hpp \
    boost/config/compiler/visualc.hpp \
    boost/config/compiler/xlcpp.hpp \
    boost/config/compiler/xlcpp_zos.hpp \
    boost/config/detail/posix_features.hpp \
    boost/config/detail/select_compiler_config.hpp \
    boost/config/detail/select_platform_config.hpp \
    boost/config/detail/select_stdlib_config.hpp \
    boost/config/detail/suffix.hpp \
    boost/config/header_deprecated.hpp \
    boost/config/helper_macros.hpp \
    boost/config/no_tr1/cmath.hpp \
    boost/config/no_tr1/complex.hpp \
    boost/config/no_tr1/functional.hpp \
    boost/config/no_tr1/memory.hpp \
    boost/config/no_tr1/utility.hpp \
    boost/config/platform/aix.hpp \
    boost/config/platform/amigaos.hpp \
    boost/config/platform/beos.hpp \
    boost/config/platform/bsd.hpp \
    boost/config/platform/cloudabi.hpp \
    boost/config/platform/cray.hpp \
    boost/config/platform/cygwin.hpp \
    boost/config/platform/haiku.hpp \
    boost/config/platform/hpux.hpp \
    boost/config/platform/irix.hpp \
    boost/config/platform/linux.hpp \
    boost/config/platform/macos.hpp \
    boost/config/platform/qnxnto.hpp \
    boost/config/platform/solaris.hpp \
    boost/config/platform/symbian.hpp \
    boost/config/platform/vms.hpp \
    boost/config/platform/vxworks.hpp \
    boost/config/platform/win32.hpp \
    boost/config/platform/zos.hpp \
    boost/config/pragma_message.hpp \
    boost/config/requires_threads.hpp \
    boost/config/stdlib/dinkumware.hpp \
    boost/config/stdlib/libcomo.hpp \
    boost/config/stdlib/libcpp.hpp \
    boost/config/stdlib/libstdcpp3.hpp \
    boost/config/stdlib/modena.hpp \
    boost/config/stdlib/msl.hpp \
    boost/config/stdlib/roguewave.hpp \
    boost/config/stdlib/sgi.hpp \
    boost/config/stdlib/stlport.hpp \
    boost/config/stdlib/vacpp.hpp \
    boost/config/stdlib/xlcpp_zos.hpp \
    boost/config/user.hpp \
    boost/config/warning_disable.hpp \
    boost/config/workaround.hpp \
    boost/coroutine/all.hpp \
    boost/coroutine/asymmetric_coroutine.hpp \
    boost/coroutine/attributes.hpp \
    boost/coroutine/coroutine.hpp \
    boost/coroutine/detail/config.hpp \
    boost/coroutine/detail/coroutine_context.hpp \
    boost/coroutine/detail/data.hpp \
    boost/coroutine/detail/flags.hpp \
    boost/coroutine/detail/parameters.hpp \
    boost/coroutine/detail/preallocated.hpp \
    boost/coroutine/detail/pull_coroutine_impl.hpp \
    boost/coroutine/detail/pull_coroutine_object.hpp \
    boost/coroutine/detail/pull_coroutine_synthesized.hpp \
    boost/coroutine/detail/push_coroutine_impl.hpp \
    boost/coroutine/detail/push_coroutine_object.hpp \
    boost/coroutine/detail/push_coroutine_synthesized.hpp \
    boost/coroutine/detail/setup.hpp \
    boost/coroutine/detail/symmetric_coroutine_call.hpp \
    boost/coroutine/detail/symmetric_coroutine_impl.hpp \
    boost/coroutine/detail/symmetric_coroutine_object.hpp \
    boost/coroutine/detail/symmetric_coroutine_yield.hpp \
    boost/coroutine/detail/trampoline.hpp \
    boost/coroutine/detail/trampoline_pull.hpp \
    boost/coroutine/detail/trampoline_push.hpp \
    boost/coroutine/exceptions.hpp \
    boost/coroutine/flags.hpp \
    boost/coroutine/posix/protected_stack_allocator.hpp \
    boost/coroutine/posix/segmented_stack_allocator.hpp \
    boost/coroutine/protected_stack_allocator.hpp \
    boost/coroutine/segmented_stack_allocator.hpp \
    boost/coroutine/stack_allocator.hpp \
    boost/coroutine/stack_context.hpp \
    boost/coroutine/stack_traits.hpp \
    boost/coroutine/standard_stack_allocator.hpp \
    boost/coroutine/symmetric_coroutine.hpp \
    boost/coroutine/windows/protected_stack_allocator.hpp \
    boost/coroutine2/all.hpp \
    boost/coroutine2/coroutine.hpp \
    boost/coroutine2/detail/config.hpp \
    boost/coroutine2/detail/coroutine.hpp \
    boost/coroutine2/detail/create_control_block.ipp \
    boost/coroutine2/detail/decay_copy.hpp \
    boost/coroutine2/detail/disable_overload.hpp \
    boost/coroutine2/detail/forced_unwind.hpp \
    boost/coroutine2/detail/pull_control_block_cc.hpp \
    boost/coroutine2/detail/pull_control_block_cc.ipp \
    boost/coroutine2/detail/pull_coroutine.hpp \
    boost/coroutine2/detail/pull_coroutine.ipp \
    boost/coroutine2/detail/push_control_block_cc.hpp \
    boost/coroutine2/detail/push_control_block_cc.ipp \
    boost/coroutine2/detail/push_coroutine.hpp \
    boost/coroutine2/detail/push_coroutine.ipp \
    boost/coroutine2/detail/state.hpp \
    boost/coroutine2/detail/wrap.hpp \
    boost/coroutine2/fixedsize_stack.hpp \
    boost/coroutine2/pooled_fixedsize_stack.hpp \
    boost/coroutine2/protected_fixedsize_stack.hpp \
    boost/coroutine2/segmented_stack.hpp \
    boost/date_time/adjust_functors.hpp \
    boost/date_time/c_local_time_adjustor.hpp \
    boost/date_time/c_time.hpp \
    boost/date_time/compiler_config.hpp \
    boost/date_time/constrained_value.hpp \
    boost/date_time/date.hpp \
    boost/date_time/date_clock_device.hpp \
    boost/date_time/date_defs.hpp \
    boost/date_time/date_duration.hpp \
    boost/date_time/date_duration_types.hpp \
    boost/date_time/date_facet.hpp \
    boost/date_time/date_format_simple.hpp \
    boost/date_time/date_formatting.hpp \
    boost/date_time/date_formatting_limited.hpp \
    boost/date_time/date_formatting_locales.hpp \
    boost/date_time/date_generator_formatter.hpp \
    boost/date_time/date_generator_parser.hpp \
    boost/date_time/date_generators.hpp \
    boost/date_time/date_iterator.hpp \
    boost/date_time/date_names_put.hpp \
    boost/date_time/date_parsing.hpp \
    boost/date_time/dst_rules.hpp \
    boost/date_time/dst_transition_generators.hpp \
    boost/date_time/filetime_functions.hpp \
    boost/date_time/find_match.hpp \
    boost/date_time/format_date_parser.hpp \
    boost/date_time/gregorian/conversion.hpp \
    boost/date_time/gregorian/formatters.hpp \
    boost/date_time/gregorian/formatters_limited.hpp \
    boost/date_time/gregorian/greg_calendar.hpp \
    boost/date_time/gregorian/greg_date.hpp \
    boost/date_time/gregorian/greg_day.hpp \
    boost/date_time/gregorian/greg_day_of_year.hpp \
    boost/date_time/gregorian/greg_duration.hpp \
    boost/date_time/gregorian/greg_duration_types.hpp \
    boost/date_time/gregorian/greg_facet.hpp \
    boost/date_time/gregorian/greg_month.hpp \
    boost/date_time/gregorian/greg_serialize.hpp \
    boost/date_time/gregorian/greg_weekday.hpp \
    boost/date_time/gregorian/greg_year.hpp \
    boost/date_time/gregorian/greg_ymd.hpp \
    boost/date_time/gregorian/gregorian.hpp \
    boost/date_time/gregorian/gregorian_io.hpp \
    boost/date_time/gregorian/gregorian_types.hpp \
    boost/date_time/gregorian/parsers.hpp \
    boost/date_time/gregorian_calendar.hpp \
    boost/date_time/int_adapter.hpp \
    boost/date_time/iso_format.hpp \
    boost/date_time/local_time/conversion.hpp \
    boost/date_time/local_time/custom_time_zone.hpp \
    boost/date_time/local_time/date_duration_operators.hpp \
    boost/date_time/local_time/dst_transition_day_rules.hpp \
    boost/date_time/local_time/local_date_time.hpp \
    boost/date_time/local_time/local_time.hpp \
    boost/date_time/local_time/local_time_io.hpp \
    boost/date_time/local_time/local_time_types.hpp \
    boost/date_time/local_time/posix_time_zone.hpp \
    boost/date_time/local_time/tz_database.hpp \
    boost/date_time/local_time_adjustor.hpp \
    boost/date_time/local_timezone_defs.hpp \
    boost/date_time/locale_config.hpp \
    boost/date_time/microsec_time_clock.hpp \
    boost/date_time/parse_format_base.hpp \
    boost/date_time/period.hpp \
    boost/date_time/period_formatter.hpp \
    boost/date_time/period_parser.hpp \
    boost/date_time/posix_time/conversion.hpp \
    boost/date_time/posix_time/date_duration_operators.hpp \
    boost/date_time/posix_time/posix_time.hpp \
    boost/date_time/posix_time/posix_time_config.hpp \
    boost/date_time/posix_time/posix_time_duration.hpp \
    boost/date_time/posix_time/posix_time_io.hpp \
    boost/date_time/posix_time/posix_time_legacy_io.hpp \
    boost/date_time/posix_time/posix_time_system.hpp \
    boost/date_time/posix_time/posix_time_types.hpp \
    boost/date_time/posix_time/ptime.hpp \
    boost/date_time/posix_time/time_formatters.hpp \
    boost/date_time/posix_time/time_formatters_limited.hpp \
    boost/date_time/posix_time/time_parsers.hpp \
    boost/date_time/posix_time/time_period.hpp \
    boost/date_time/posix_time/time_serialize.hpp \
    boost/date_time/special_defs.hpp \
    boost/date_time/special_values_formatter.hpp \
    boost/date_time/special_values_parser.hpp \
    boost/date_time/string_convert.hpp \
    boost/date_time/string_parse_tree.hpp \
    boost/date_time/strings_from_facet.hpp \
    boost/date_time/time.hpp \
    boost/date_time/time_clock.hpp \
    boost/date_time/time_defs.hpp \
    boost/date_time/time_duration.hpp \
    boost/date_time/time_facet.hpp \
    boost/date_time/time_formatting_streams.hpp \
    boost/date_time/time_iterator.hpp \
    boost/date_time/time_parsing.hpp \
    boost/date_time/time_resolution_traits.hpp \
    boost/date_time/time_system_counted.hpp \
    boost/date_time/time_system_split.hpp \
    boost/date_time/time_zone_base.hpp \
    boost/date_time/time_zone_names.hpp \
    boost/date_time/tz_db_base.hpp \
    boost/date_time/wrapping_int.hpp \
    boost/date_time/year_month_day.hpp \
    boost/detail/algorithm.hpp \
    boost/detail/allocator_utilities.hpp \
    boost/detail/atomic_count.hpp \
    boost/detail/basic_pointerbuf.hpp \
    boost/detail/binary_search.hpp \
    boost/detail/bitmask.hpp \
    boost/detail/call_traits.hpp \
    boost/detail/catch_exceptions.hpp \
    boost/detail/compressed_pair.hpp \
    boost/detail/container_fwd.hpp \
    boost/detail/fenv.hpp \
    boost/detail/has_default_constructor.hpp \
    boost/detail/identifier.hpp \
    boost/detail/indirect_traits.hpp \
    boost/detail/interlocked.hpp \
    boost/detail/is_incrementable.hpp \
    boost/detail/is_sorted.hpp \
    boost/detail/is_xxx.hpp \
    boost/detail/iterator.hpp \
    boost/detail/lcast_precision.hpp \
    boost/detail/lightweight_main.hpp \
    boost/detail/lightweight_mutex.hpp \
    boost/detail/lightweight_test.hpp \
    boost/detail/lightweight_test_report.hpp \
    boost/detail/lightweight_thread.hpp \
    boost/detail/named_template_params.hpp \
    boost/detail/no_exceptions_support.hpp \
    boost/detail/numeric_traits.hpp \
    boost/detail/ob_compressed_pair.hpp \
    boost/detail/quick_allocator.hpp \
    boost/detail/reference_content.hpp \
    boost/detail/scoped_enum_emulation.hpp \
    boost/detail/select_type.hpp \
    boost/detail/sp_typeinfo.hpp \
    boost/detail/templated_streams.hpp \
    boost/detail/utf8_codecvt_facet.hpp \
    boost/detail/utf8_codecvt_facet.ipp \
    boost/detail/winapi/access_rights.hpp \
    boost/detail/winapi/apc.hpp \
    boost/detail/winapi/basic_types.hpp \
    boost/detail/winapi/bcrypt.hpp \
    boost/detail/winapi/character_code_conversion.hpp \
    boost/detail/winapi/condition_variable.hpp \
    boost/detail/winapi/config.hpp \
    boost/detail/winapi/critical_section.hpp \
    boost/detail/winapi/crypt.hpp \
    boost/detail/winapi/dbghelp.hpp \
    boost/detail/winapi/debugapi.hpp \
    boost/detail/winapi/detail/deprecated_namespace.hpp \
    boost/detail/winapi/directory_management.hpp \
    boost/detail/winapi/dll.hpp \
    boost/detail/winapi/environment.hpp \
    boost/detail/winapi/error_codes.hpp \
    boost/detail/winapi/error_handling.hpp \
    boost/detail/winapi/event.hpp \
    boost/detail/winapi/file_management.hpp \
    boost/detail/winapi/file_mapping.hpp \
    boost/detail/winapi/get_current_process.hpp \
    boost/detail/winapi/get_current_process_id.hpp \
    boost/detail/winapi/get_current_thread.hpp \
    boost/detail/winapi/get_current_thread_id.hpp \
    boost/detail/winapi/get_last_error.hpp \
    boost/detail/winapi/get_process_times.hpp \
    boost/detail/winapi/get_system_directory.hpp \
    boost/detail/winapi/get_thread_times.hpp \
    boost/detail/winapi/handle_info.hpp \
    boost/detail/winapi/handles.hpp \
    boost/detail/winapi/heap_memory.hpp \
    boost/detail/winapi/init_once.hpp \
    boost/detail/winapi/jobs.hpp \
    boost/detail/winapi/limits.hpp \
    boost/detail/winapi/local_memory.hpp \
    boost/detail/winapi/memory.hpp \
    boost/detail/winapi/mutex.hpp \
    boost/detail/winapi/overlapped.hpp \
    boost/detail/winapi/page_protection_flags.hpp \
    boost/detail/winapi/pipes.hpp \
    boost/detail/winapi/priority_class.hpp \
    boost/detail/winapi/process.hpp \
    boost/detail/winapi/security.hpp \
    boost/detail/winapi/semaphore.hpp \
    boost/detail/winapi/shell.hpp \
    boost/detail/winapi/show_window.hpp \
    boost/detail/winapi/srw_lock.hpp \
    boost/detail/winapi/stack_backtrace.hpp \
    boost/detail/winapi/synchronization.hpp \
    boost/detail/winapi/system.hpp \
    boost/detail/winapi/thread.hpp \
    boost/detail/winapi/thread_pool.hpp \
    boost/detail/winapi/time.hpp \
    boost/detail/winapi/timers.hpp \
    boost/detail/winapi/tls.hpp \
    boost/detail/winapi/wait.hpp \
    boost/detail/winapi/waitable_timer.hpp \
    boost/detail/workaround.hpp \
    boost/regex/concepts.hpp \
    boost/regex/config.hpp \
    boost/regex/config/borland.hpp \
    boost/regex/config/cwchar.hpp \
    boost/regex/icu.hpp \
    boost/regex/mfc.hpp \
    boost/regex/pattern_except.hpp \
    boost/regex/pending/object_cache.hpp \
    boost/regex/pending/static_mutex.hpp \
    boost/regex/pending/unicode_iterator.hpp \
    boost/regex/regex_traits.hpp \
    boost/regex/user.hpp \
    boost/regex/v4/basic_regex.hpp \
    boost/regex/v4/basic_regex_creator.hpp \
    boost/regex/v4/basic_regex_parser.hpp \
    boost/regex/v4/c_regex_traits.hpp \
    boost/regex/v4/char_regex_traits.hpp \
    boost/regex/v4/cpp_regex_traits.hpp \
    boost/regex/v4/cregex.hpp \
    boost/regex/v4/error_type.hpp \
    boost/regex/v4/fileiter.hpp \
    boost/regex/v4/instances.hpp \
    boost/regex/v4/iterator_category.hpp \
    boost/regex/v4/iterator_traits.hpp \
    boost/regex/v4/match_flags.hpp \
    boost/regex/v4/match_results.hpp \
    boost/regex/v4/mem_block_cache.hpp \
    boost/regex/v4/perl_matcher.hpp \
    boost/regex/v4/perl_matcher_common.hpp \
    boost/regex/v4/perl_matcher_non_recursive.hpp \
    boost/regex/v4/perl_matcher_recursive.hpp \
    boost/regex/v4/primary_transform.hpp \
    boost/regex/v4/protected_call.hpp \
    boost/regex/v4/regbase.hpp \
    boost/regex/v4/regex.hpp \
    boost/regex/v4/regex_format.hpp \
    boost/regex/v4/regex_fwd.hpp \
    boost/regex/v4/regex_grep.hpp \
    boost/regex/v4/regex_iterator.hpp \
    boost/regex/v4/regex_match.hpp \
    boost/regex/v4/regex_merge.hpp \
    boost/regex/v4/regex_raw_buffer.hpp \
    boost/regex/v4/regex_replace.hpp \
    boost/regex/v4/regex_search.hpp \
    boost/regex/v4/regex_split.hpp \
    boost/regex/v4/regex_token_iterator.hpp \
    boost/regex/v4/regex_traits.hpp \
    boost/regex/v4/regex_traits_defaults.hpp \
    boost/regex/v4/regex_workaround.hpp \
    boost/regex/v4/states.hpp \
    boost/regex/v4/sub_match.hpp \
    boost/regex/v4/syntax_type.hpp \
    boost/regex/v4/u32regex_iterator.hpp \
    boost/regex/v4/u32regex_token_iterator.hpp \
    boost/regex/v4/w32_regex_traits.hpp \
    boost/serialization/access.hpp \
    boost/serialization/archive_input_unordered_map.hpp \
    boost/serialization/archive_input_unordered_set.hpp \
    boost/serialization/array.hpp \
    boost/serialization/array_optimization.hpp \
    boost/serialization/array_wrapper.hpp \
    boost/serialization/assume_abstract.hpp \
    boost/serialization/base_object.hpp \
    boost/serialization/binary_object.hpp \
    boost/serialization/bitset.hpp \
    boost/serialization/boost_array.hpp \
    boost/serialization/boost_unordered_map.hpp \
    boost/serialization/boost_unordered_set.hpp \
    boost/serialization/collection_size_type.hpp \
    boost/serialization/collection_traits.hpp \
    boost/serialization/collections_load_imp.hpp \
    boost/serialization/collections_save_imp.hpp \
    boost/serialization/complex.hpp \
    boost/serialization/config.hpp \
    boost/serialization/deque.hpp \
    boost/serialization/detail/is_default_constructible.hpp \
    boost/serialization/detail/shared_count_132.hpp \
    boost/serialization/detail/shared_ptr_132.hpp \
    boost/serialization/detail/shared_ptr_nmt_132.hpp \
    boost/serialization/detail/stack_constructor.hpp \
    boost/serialization/export.hpp \
    boost/serialization/extended_type_info.hpp \
    boost/serialization/extended_type_info_no_rtti.hpp \
    boost/serialization/extended_type_info_typeid.hpp \
    boost/serialization/factory.hpp \
    boost/serialization/force_include.hpp \
    boost/serialization/forward_list.hpp \
    boost/serialization/hash_collections_load_imp.hpp \
    boost/serialization/hash_collections_save_imp.hpp \
    boost/serialization/hash_map.hpp \
    boost/serialization/hash_set.hpp \
    boost/serialization/is_bitwise_serializable.hpp \
    boost/serialization/item_version_type.hpp \
    boost/serialization/level.hpp \
    boost/serialization/level_enum.hpp \
    boost/serialization/list.hpp \
    boost/serialization/map.hpp \
    boost/serialization/nvp.hpp \
    boost/serialization/optional.hpp \
    boost/serialization/priority_queue.hpp \
    boost/serialization/queue.hpp \
    boost/serialization/scoped_ptr.hpp \
    boost/serialization/serialization.hpp \
    boost/serialization/set.hpp \
    boost/serialization/shared_ptr.hpp \
    boost/serialization/shared_ptr_132.hpp \
    boost/serialization/shared_ptr_helper.hpp \
    boost/serialization/singleton.hpp \
    boost/serialization/slist.hpp \
    boost/serialization/smart_cast.hpp \
    boost/serialization/split_free.hpp \
    boost/serialization/split_member.hpp \
    boost/serialization/stack.hpp \
    boost/serialization/state_saver.hpp \
    boost/serialization/static_warning.hpp \
    boost/serialization/string.hpp \
    boost/serialization/strong_typedef.hpp \
    boost/serialization/throw_exception.hpp \
    boost/serialization/tracking.hpp \
    boost/serialization/tracking_enum.hpp \
    boost/serialization/traits.hpp \
    boost/serialization/type_info_implementation.hpp \
    boost/serialization/unique_ptr.hpp \
    boost/serialization/unordered_collections_load_imp.hpp \
    boost/serialization/unordered_collections_save_imp.hpp \
    boost/serialization/unordered_map.hpp \
    boost/serialization/unordered_set.hpp \
    boost/serialization/utility.hpp \
    boost/serialization/valarray.hpp \
    boost/serialization/variant.hpp \
    boost/serialization/vector.hpp \
    boost/serialization/vector_135.hpp \
    boost/serialization/version.hpp \
    boost/serialization/void_cast.hpp \
    boost/serialization/void_cast_fwd.hpp \
    boost/serialization/weak_ptr.hpp \
    boost/serialization/wrapper.hpp \
    boost/system/api_config.hpp \
    boost/system/config.hpp \
    boost/system/cygwin_error.hpp \
    boost/system/detail/config.hpp \
    boost/system/detail/generic_category.hpp \
    boost/system/detail/std_interoperability.hpp \
    boost/system/detail/system_category_posix.hpp \
    boost/system/detail/system_category_win32.hpp \
    boost/system/error_code.hpp \
    boost/system/linux_error.hpp \
    boost/system/system_error.hpp \
    boost/system/windows_error.hpp \
    boost/thread/barrier.hpp \
    boost/thread/caller_context.hpp \
    boost/thread/completion_latch.hpp \
    boost/thread/concurrent_queues/deque_adaptor.hpp \
    boost/thread/concurrent_queues/deque_base.hpp \
    boost/thread/concurrent_queues/deque_views.hpp \
    boost/thread/concurrent_queues/detail/sync_deque_base.hpp \
    boost/thread/concurrent_queues/detail/sync_queue_base.hpp \
    boost/thread/concurrent_queues/queue_adaptor.hpp \
    boost/thread/concurrent_queues/queue_base.hpp \
    boost/thread/concurrent_queues/queue_op_status.hpp \
    boost/thread/concurrent_queues/queue_views.hpp \
    boost/thread/concurrent_queues/sync_bounded_queue.hpp \
    boost/thread/concurrent_queues/sync_deque.hpp \
    boost/thread/concurrent_queues/sync_priority_queue.hpp \
    boost/thread/concurrent_queues/sync_queue.hpp \
    boost/thread/concurrent_queues/sync_timed_queue.hpp \
    boost/thread/condition.hpp \
    boost/thread/condition_variable.hpp \
    boost/thread/csbl/deque.hpp \
    boost/thread/csbl/devector.hpp \
    boost/thread/csbl/functional.hpp \
    boost/thread/csbl/list.hpp \
    boost/thread/csbl/memory.hpp \
    boost/thread/csbl/memory/allocator_arg.hpp \
    boost/thread/csbl/memory/allocator_traits.hpp \
    boost/thread/csbl/memory/config.hpp \
    boost/thread/csbl/memory/default_delete.hpp \
    boost/thread/csbl/memory/pointer_traits.hpp \
    boost/thread/csbl/memory/scoped_allocator.hpp \
    boost/thread/csbl/memory/shared_ptr.hpp \
    boost/thread/csbl/memory/unique_ptr.hpp \
    boost/thread/csbl/queue.hpp \
    boost/thread/csbl/tuple.hpp \
    boost/thread/csbl/vector.hpp \
    boost/thread/cv_status.hpp \
    boost/thread/detail/atomic_redef_macros.hpp \
    boost/thread/detail/atomic_undef_macros.hpp \
    boost/thread/detail/config.hpp \
    boost/thread/detail/counter.hpp \
    boost/thread/detail/delete.hpp \
    boost/thread/detail/force_cast.hpp \
    boost/thread/detail/function_wrapper.hpp \
    boost/thread/detail/invoke.hpp \
    boost/thread/detail/invoker.hpp \
    boost/thread/detail/is_convertible.hpp \
    boost/thread/detail/lockable_wrapper.hpp \
    boost/thread/detail/log.hpp \
    boost/thread/detail/make_tuple_indices.hpp \
    boost/thread/detail/memory.hpp \
    boost/thread/detail/move.hpp \
    boost/thread/detail/nullary_function.hpp \
    boost/thread/detail/platform.hpp \
    boost/thread/detail/platform_time.hpp \
    boost/thread/detail/singleton.hpp \
    boost/thread/detail/thread.hpp \
    boost/thread/detail/thread_group.hpp \
    boost/thread/detail/thread_heap_alloc.hpp \
    boost/thread/detail/thread_interruption.hpp \
    boost/thread/detail/thread_safety.hpp \
    boost/thread/detail/tss_hooks.hpp \
    boost/thread/detail/variadic_footer.hpp \
    boost/thread/detail/variadic_header.hpp \
    boost/thread/exceptional_ptr.hpp \
    boost/thread/exceptions.hpp \
    boost/thread/executor.hpp \
    boost/thread/executors/basic_thread_pool.hpp \
    boost/thread/executors/detail/priority_executor_base.hpp \
    boost/thread/executors/detail/scheduled_executor_base.hpp \
    boost/thread/executors/executor.hpp \
    boost/thread/executors/executor_adaptor.hpp \
    boost/thread/executors/generic_executor_ref.hpp \
    boost/thread/executors/inline_executor.hpp \
    boost/thread/executors/loop_executor.hpp \
    boost/thread/executors/scheduled_thread_pool.hpp \
    boost/thread/executors/scheduler.hpp \
    boost/thread/executors/scheduling_adaptor.hpp \
    boost/thread/executors/serial_executor.hpp \
    boost/thread/executors/serial_executor_cont.hpp \
    boost/thread/executors/thread_executor.hpp \
    boost/thread/executors/work.hpp \
    boost/thread/experimental/config/inline_namespace.hpp \
    boost/thread/experimental/exception_list.hpp \
    boost/thread/experimental/parallel/v1/exception_list.hpp \
    boost/thread/experimental/parallel/v1/inline_namespace.hpp \
    boost/thread/experimental/parallel/v2/inline_namespace.hpp \
    boost/thread/experimental/parallel/v2/task_region.hpp \
    boost/thread/experimental/task_region.hpp \
    boost/thread/externally_locked.hpp \
    boost/thread/externally_locked_stream.hpp \
    boost/thread/future.hpp \
    boost/thread/futures/future_error.hpp \
    boost/thread/futures/future_error_code.hpp \
    boost/thread/futures/future_status.hpp \
    boost/thread/futures/is_future_type.hpp \
    boost/thread/futures/launch.hpp \
    boost/thread/futures/wait_for_all.hpp \
    boost/thread/futures/wait_for_any.hpp \
    boost/thread/interruption.hpp \
    boost/thread/is_locked_by_this_thread.hpp \
    boost/thread/latch.hpp \
    boost/thread/lock_algorithms.hpp \
    boost/thread/lock_concepts.hpp \
    boost/thread/lock_factories.hpp \
    boost/thread/lock_guard.hpp \
    boost/thread/lock_options.hpp \
    boost/thread/lock_traits.hpp \
    boost/thread/lock_types.hpp \
    boost/thread/lockable_adapter.hpp \
    boost/thread/lockable_concepts.hpp \
    boost/thread/lockable_traits.hpp \
    boost/thread/locks.hpp \
    boost/thread/mutex.hpp \
    boost/thread/null_mutex.hpp \
    boost/thread/once.hpp \
    boost/thread/ostream_buffer.hpp \
    boost/thread/poly_lockable.hpp \
    boost/thread/poly_lockable_adapter.hpp \
    boost/thread/poly_shared_lockable.hpp \
    boost/thread/poly_shared_lockable_adapter.hpp \
    boost/thread/pthread/condition_variable.hpp \
    boost/thread/pthread/condition_variable_fwd.hpp \
    boost/thread/pthread/mutex.hpp \
    boost/thread/pthread/once.hpp \
    boost/thread/pthread/once_atomic.hpp \
    boost/thread/pthread/pthread_helpers.hpp \
    boost/thread/pthread/pthread_mutex_scoped_lock.hpp \
    boost/thread/pthread/recursive_mutex.hpp \
    boost/thread/pthread/shared_mutex.hpp \
    boost/thread/pthread/thread_data.hpp \
    boost/thread/pthread/thread_heap_alloc.hpp \
    boost/thread/recursive_mutex.hpp \
    boost/thread/reverse_lock.hpp \
    boost/thread/scoped_thread.hpp \
    boost/thread/shared_lock_guard.hpp \
    boost/thread/shared_mutex.hpp \
    boost/thread/strict_lock.hpp \
    boost/thread/sync_bounded_queue.hpp \
    boost/thread/sync_queue.hpp \
    boost/thread/synchronized_value.hpp \
    boost/thread/testable_mutex.hpp \
    boost/thread/thread.hpp \
    boost/thread/thread_functors.hpp \
    boost/thread/thread_guard.hpp \
    boost/thread/thread_only.hpp \
    boost/thread/thread_pool.hpp \
    boost/thread/thread_time.hpp \
    boost/thread/tss.hpp \
    boost/thread/user_scheduler.hpp \
    boost/thread/v2/shared_mutex.hpp \
    boost/thread/win32/basic_recursive_mutex.hpp \
    boost/thread/win32/basic_timed_mutex.hpp \
    boost/thread/win32/condition_variable.hpp \
    boost/thread/win32/interlocked_read.hpp \
    boost/thread/win32/mfc_thread_init.hpp \
    boost/thread/win32/mutex.hpp \
    boost/thread/win32/once.hpp \
    boost/thread/win32/recursive_mutex.hpp \
    boost/thread/win32/shared_mutex.hpp \
    boost/thread/win32/thread_data.hpp \
    boost/thread/win32/thread_heap_alloc.hpp \
    boost/thread/win32/thread_primitives.hpp \
    boost/thread/with_lock_guard.hpp \
    boost/thread/xtime.hpp \
    websocketpp/base64/base64.hpp \
    websocketpp/client.hpp \
    websocketpp/close.hpp \
    websocketpp/common/asio.hpp \
    websocketpp/common/asio_ssl.hpp \
    websocketpp/common/chrono.hpp \
    websocketpp/common/connection_hdl.hpp \
    websocketpp/common/cpp11.hpp \
    websocketpp/common/functional.hpp \
    websocketpp/common/md5.hpp \
    websocketpp/common/memory.hpp \
    websocketpp/common/network.hpp \
    websocketpp/common/platforms.hpp \
    websocketpp/common/random.hpp \
    websocketpp/common/regex.hpp \
    websocketpp/common/stdint.hpp \
    websocketpp/common/system_error.hpp \
    websocketpp/common/thread.hpp \
    websocketpp/common/time.hpp \
    websocketpp/common/type_traits.hpp \
    websocketpp/concurrency/basic.hpp \
    websocketpp/concurrency/none.hpp \
    websocketpp/config/asio.hpp \
    websocketpp/config/asio_client.hpp \
    websocketpp/config/asio_no_tls.hpp \
    websocketpp/config/asio_no_tls_client.hpp \
    websocketpp/config/boost_config.hpp \
    websocketpp/config/core.hpp \
    websocketpp/config/core_client.hpp \
    websocketpp/config/debug.hpp \
    websocketpp/config/debug_asio.hpp \
    websocketpp/config/debug_asio_no_tls.hpp \
    websocketpp/config/minimal_client.hpp \
    websocketpp/config/minimal_server.hpp \
    websocketpp/connection.hpp \
    websocketpp/connection_base.hpp \
    websocketpp/endpoint.hpp \
    websocketpp/endpoint_base.hpp \
    websocketpp/error.hpp \
    websocketpp/extensions/extension.hpp \
    websocketpp/extensions/permessage_deflate/disabled.hpp \
    websocketpp/extensions/permessage_deflate/enabled.hpp \
    websocketpp/frame.hpp \
    websocketpp/http/constants.hpp \
    websocketpp/http/impl/parser.hpp \
    websocketpp/http/impl/request.hpp \
    websocketpp/http/impl/response.hpp \
    websocketpp/http/parser.hpp \
    websocketpp/http/request.hpp \
    websocketpp/http/response.hpp \
    websocketpp/impl/connection_impl.hpp \
    websocketpp/impl/endpoint_impl.hpp \
    websocketpp/impl/utilities_impl.hpp \
    websocketpp/logger/basic.hpp \
    websocketpp/logger/levels.hpp \
    websocketpp/logger/stub.hpp \
    websocketpp/logger/syslog.hpp \
    websocketpp/message_buffer/alloc.hpp \
    websocketpp/message_buffer/message.hpp \
    websocketpp/message_buffer/pool.hpp \
    websocketpp/processors/base.hpp \
    websocketpp/processors/hybi00.hpp \
    websocketpp/processors/hybi07.hpp \
    websocketpp/processors/hybi08.hpp \
    websocketpp/processors/hybi13.hpp \
    websocketpp/processors/processor.hpp \
    websocketpp/random/none.hpp \
    websocketpp/random/random_device.hpp \
    websocketpp/roles/client_endpoint.hpp \
    websocketpp/roles/server_endpoint.hpp \
    websocketpp/server.hpp \
    websocketpp/sha1/sha1.hpp \
    websocketpp/transport/asio/base.hpp \
    websocketpp/transport/asio/connection.hpp \
    websocketpp/transport/asio/endpoint.hpp \
    websocketpp/transport/asio/security/base.hpp \
    websocketpp/transport/asio/security/none.hpp \
    websocketpp/transport/asio/security/tls.hpp \
    websocketpp/transport/base/connection.hpp \
    websocketpp/transport/base/endpoint.hpp \
    websocketpp/transport/debug/base.hpp \
    websocketpp/transport/debug/connection.hpp \
    websocketpp/transport/debug/endpoint.hpp \
    websocketpp/transport/iostream/base.hpp \
    websocketpp/transport/iostream/connection.hpp \
    websocketpp/transport/iostream/endpoint.hpp \
    websocketpp/transport/stub/base.hpp \
    websocketpp/transport/stub/connection.hpp \
    websocketpp/transport/stub/endpoint.hpp \
    websocketpp/uri.hpp \
    websocketpp/utf8_validator.hpp \
    websocketpp/utilities.hpp \
    websocketpp/version.hpp

LIBS += -L$$PWD/lib/ -llibboost_thread-mgw8-mt-d-x32-1_73 \
        -L$$PWD/lib/ -llibboost_thread-mgw8-mt-x32-1_73 \
        -L$$PWD/lib/ -llibboost_system-mgw8-mt-x32-1_73 \
        -L$$PWD/lib/ -llibboost_system-mgw8-mt-d-x32-1_73 \
        -L$$PWD/lib/ -llibboost_serialization-mgw8-mt-x32-1_73 \
        -L$$PWD/lib/ -llibboost_serialization-mgw8-mt-d-x32-1_73 \
        -L$$PWD/lib/ -llibboost_regex-mgw8-mt-x32-1_73 \
        -L$$PWD/lib/ -llibboost_regex-mgw8-mt-d-x32-1_73 \
        -L$$PWD/lib/ -llibboost_date_time-mgw8-mt-x32-1_73 \
        -L$$PWD/lib/ -llibboost_date_time-mgw8-mt-d-x32-1_73 \
        -L$$PWD/lib/ -llibboost_coroutine-mgw8-mt-x32-1_73 \
        -L$$PWD/lib/ -llibboost_coroutine-mgw8-mt-d-x32-1_73 \

