QT -= gui

CONFIG += c++11 console
CONFIG -= app_bundle

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

LIBS += -L"lib/" -llibboost_thread-mgw8-mt-d-x32-1_73

SOURCES += \
        main.cpp

DISTFILES += \
    lib/libboost_thread-mgw8-mt-d-x32-1_73.a \
    lib/libboost_thread-mgw8-mt-x32-1_73.a \ \
    websocketpp/CMakeLists.txt

HEADERS += \
    boost/thread/barrier.hpp \
    boost/thread/caller_context.hpp \
    boost/thread/completion_latch.hpp \
    boost/thread/concurrent_queues/deque_adaptor.hpp \
    boost/thread/concurrent_queues/deque_base.hpp \
    boost/thread/concurrent_queues/deque_views.hpp \
    boost/thread/concurrent_queues/detail/sync_deque_base.hpp \
    boost/thread/concurrent_queues/detail/sync_queue_base.hpp \
    boost/thread/concurrent_queues/queue_adaptor.hpp \
    boost/thread/concurrent_queues/queue_base.hpp \
    boost/thread/concurrent_queues/queue_op_status.hpp \
    boost/thread/concurrent_queues/queue_views.hpp \
    boost/thread/concurrent_queues/sync_bounded_queue.hpp \
    boost/thread/concurrent_queues/sync_deque.hpp \
    boost/thread/concurrent_queues/sync_priority_queue.hpp \
    boost/thread/concurrent_queues/sync_queue.hpp \
    boost/thread/concurrent_queues/sync_timed_queue.hpp \
    boost/thread/condition.hpp \
    boost/thread/condition_variable.hpp \
    boost/thread/csbl/deque.hpp \
    boost/thread/csbl/devector.hpp \
    boost/thread/csbl/functional.hpp \
    boost/thread/csbl/list.hpp \
    boost/thread/csbl/memory.hpp \
    boost/thread/csbl/memory/allocator_arg.hpp \
    boost/thread/csbl/memory/allocator_traits.hpp \
    boost/thread/csbl/memory/config.hpp \
    boost/thread/csbl/memory/default_delete.hpp \
    boost/thread/csbl/memory/pointer_traits.hpp \
    boost/thread/csbl/memory/scoped_allocator.hpp \
    boost/thread/csbl/memory/shared_ptr.hpp \
    boost/thread/csbl/memory/unique_ptr.hpp \
    boost/thread/csbl/queue.hpp \
    boost/thread/csbl/tuple.hpp \
    boost/thread/csbl/vector.hpp \
    boost/thread/cv_status.hpp \
    boost/thread/detail/atomic_redef_macros.hpp \
    boost/thread/detail/atomic_undef_macros.hpp \
    boost/thread/detail/config.hpp \
    boost/thread/detail/counter.hpp \
    boost/thread/detail/delete.hpp \
    boost/thread/detail/force_cast.hpp \
    boost/thread/detail/function_wrapper.hpp \
    boost/thread/detail/invoke.hpp \
    boost/thread/detail/invoker.hpp \
    boost/thread/detail/is_convertible.hpp \
    boost/thread/detail/lockable_wrapper.hpp \
    boost/thread/detail/log.hpp \
    boost/thread/detail/make_tuple_indices.hpp \
    boost/thread/detail/memory.hpp \
    boost/thread/detail/move.hpp \
    boost/thread/detail/nullary_function.hpp \
    boost/thread/detail/platform.hpp \
    boost/thread/detail/platform_time.hpp \
    boost/thread/detail/singleton.hpp \
    boost/thread/detail/thread.hpp \
    boost/thread/detail/thread_group.hpp \
    boost/thread/detail/thread_heap_alloc.hpp \
    boost/thread/detail/thread_interruption.hpp \
    boost/thread/detail/thread_safety.hpp \
    boost/thread/detail/tss_hooks.hpp \
    boost/thread/detail/variadic_footer.hpp \
    boost/thread/detail/variadic_header.hpp \
    boost/thread/exceptional_ptr.hpp \
    boost/thread/exceptions.hpp \
    boost/thread/executor.hpp \
    boost/thread/executors/basic_thread_pool.hpp \
    boost/thread/executors/detail/priority_executor_base.hpp \
    boost/thread/executors/detail/scheduled_executor_base.hpp \
    boost/thread/executors/executor.hpp \
    boost/thread/executors/executor_adaptor.hpp \
    boost/thread/executors/generic_executor_ref.hpp \
    boost/thread/executors/inline_executor.hpp \
    boost/thread/executors/loop_executor.hpp \
    boost/thread/executors/scheduled_thread_pool.hpp \
    boost/thread/executors/scheduler.hpp \
    boost/thread/executors/scheduling_adaptor.hpp \
    boost/thread/executors/serial_executor.hpp \
    boost/thread/executors/serial_executor_cont.hpp \
    boost/thread/executors/thread_executor.hpp \
    boost/thread/executors/work.hpp \
    boost/thread/experimental/config/inline_namespace.hpp \
    boost/thread/experimental/exception_list.hpp \
    boost/thread/experimental/parallel/v1/exception_list.hpp \
    boost/thread/experimental/parallel/v1/inline_namespace.hpp \
    boost/thread/experimental/parallel/v2/inline_namespace.hpp \
    boost/thread/experimental/parallel/v2/task_region.hpp \
    boost/thread/experimental/task_region.hpp \
    boost/thread/externally_locked.hpp \
    boost/thread/externally_locked_stream.hpp \
    boost/thread/future.hpp \
    boost/thread/futures/future_error.hpp \
    boost/thread/futures/future_error_code.hpp \
    boost/thread/futures/future_status.hpp \
    boost/thread/futures/is_future_type.hpp \
    boost/thread/futures/launch.hpp \
    boost/thread/futures/wait_for_all.hpp \
    boost/thread/futures/wait_for_any.hpp \
    boost/thread/interruption.hpp \
    boost/thread/is_locked_by_this_thread.hpp \
    boost/thread/latch.hpp \
    boost/thread/lock_algorithms.hpp \
    boost/thread/lock_concepts.hpp \
    boost/thread/lock_factories.hpp \
    boost/thread/lock_guard.hpp \
    boost/thread/lock_options.hpp \
    boost/thread/lock_traits.hpp \
    boost/thread/lock_types.hpp \
    boost/thread/lockable_adapter.hpp \
    boost/thread/lockable_concepts.hpp \
    boost/thread/lockable_traits.hpp \
    boost/thread/locks.hpp \
    boost/thread/mutex.hpp \
    boost/thread/null_mutex.hpp \
    boost/thread/once.hpp \
    boost/thread/ostream_buffer.hpp \
    boost/thread/poly_lockable.hpp \
    boost/thread/poly_lockable_adapter.hpp \
    boost/thread/poly_shared_lockable.hpp \
    boost/thread/poly_shared_lockable_adapter.hpp \
    boost/thread/pthread/condition_variable.hpp \
    boost/thread/pthread/condition_variable_fwd.hpp \
    boost/thread/pthread/mutex.hpp \
    boost/thread/pthread/once.hpp \
    boost/thread/pthread/once_atomic.hpp \
    boost/thread/pthread/pthread_helpers.hpp \
    boost/thread/pthread/pthread_mutex_scoped_lock.hpp \
    boost/thread/pthread/recursive_mutex.hpp \
    boost/thread/pthread/shared_mutex.hpp \
    boost/thread/pthread/thread_data.hpp \
    boost/thread/pthread/thread_heap_alloc.hpp \
    boost/thread/recursive_mutex.hpp \
    boost/thread/reverse_lock.hpp \
    boost/thread/scoped_thread.hpp \
    boost/thread/shared_lock_guard.hpp \
    boost/thread/shared_mutex.hpp \
    boost/thread/strict_lock.hpp \
    boost/thread/sync_bounded_queue.hpp \
    boost/thread/sync_queue.hpp \
    boost/thread/synchronized_value.hpp \
    boost/thread/testable_mutex.hpp \
    boost/thread/thread.hpp \
    boost/thread/thread_functors.hpp \
    boost/thread/thread_guard.hpp \
    boost/thread/thread_only.hpp \
    boost/thread/thread_pool.hpp \
    boost/thread/thread_time.hpp \
    boost/thread/tss.hpp \
    boost/thread/user_scheduler.hpp \
    boost/thread/v2/shared_mutex.hpp \
    boost/thread/win32/basic_recursive_mutex.hpp \
    boost/thread/win32/basic_timed_mutex.hpp \
    boost/thread/win32/condition_variable.hpp \
    boost/thread/win32/interlocked_read.hpp \
    boost/thread/win32/mfc_thread_init.hpp \
    boost/thread/win32/mutex.hpp \
    boost/thread/win32/once.hpp \
    boost/thread/win32/recursive_mutex.hpp \
    boost/thread/win32/shared_mutex.hpp \
    boost/thread/win32/thread_data.hpp \
    boost/thread/win32/thread_heap_alloc.hpp \
    boost/thread/win32/thread_primitives.hpp \
    boost/thread/with_lock_guard.hpp \
    boost/thread/xtime.hpp \
    websocketpp/base64/base64.hpp \
    websocketpp/client.hpp \
    websocketpp/close.hpp \
    websocketpp/common/asio.hpp \
    websocketpp/common/asio_ssl.hpp \
    websocketpp/common/chrono.hpp \
    websocketpp/common/connection_hdl.hpp \
    websocketpp/common/cpp11.hpp \
    websocketpp/common/functional.hpp \
    websocketpp/common/md5.hpp \
    websocketpp/common/memory.hpp \
    websocketpp/common/network.hpp \
    websocketpp/common/platforms.hpp \
    websocketpp/common/random.hpp \
    websocketpp/common/regex.hpp \
    websocketpp/common/stdint.hpp \
    websocketpp/common/system_error.hpp \
    websocketpp/common/thread.hpp \
    websocketpp/common/time.hpp \
    websocketpp/common/type_traits.hpp \
    websocketpp/concurrency/basic.hpp \
    websocketpp/concurrency/none.hpp \
    websocketpp/config/asio.hpp \
    websocketpp/config/asio_client.hpp \
    websocketpp/config/asio_no_tls.hpp \
    websocketpp/config/asio_no_tls_client.hpp \
    websocketpp/config/boost_config.hpp \
    websocketpp/config/core.hpp \
    websocketpp/config/core_client.hpp \
    websocketpp/config/debug.hpp \
    websocketpp/config/debug_asio.hpp \
    websocketpp/config/debug_asio_no_tls.hpp \
    websocketpp/config/minimal_client.hpp \
    websocketpp/config/minimal_server.hpp \
    websocketpp/connection.hpp \
    websocketpp/connection_base.hpp \
    websocketpp/endpoint.hpp \
    websocketpp/endpoint_base.hpp \
    websocketpp/error.hpp \
    websocketpp/extensions/extension.hpp \
    websocketpp/extensions/permessage_deflate/disabled.hpp \
    websocketpp/extensions/permessage_deflate/enabled.hpp \
    websocketpp/frame.hpp \
    websocketpp/http/constants.hpp \
    websocketpp/http/impl/parser.hpp \
    websocketpp/http/impl/request.hpp \
    websocketpp/http/impl/response.hpp \
    websocketpp/http/parser.hpp \
    websocketpp/http/request.hpp \
    websocketpp/http/response.hpp \
    websocketpp/impl/connection_impl.hpp \
    websocketpp/impl/endpoint_impl.hpp \
    websocketpp/impl/utilities_impl.hpp \
    websocketpp/logger/basic.hpp \
    websocketpp/logger/levels.hpp \
    websocketpp/logger/stub.hpp \
    websocketpp/logger/syslog.hpp \
    websocketpp/message_buffer/alloc.hpp \
    websocketpp/message_buffer/message.hpp \
    websocketpp/message_buffer/pool.hpp \
    websocketpp/processors/base.hpp \
    websocketpp/processors/hybi00.hpp \
    websocketpp/processors/hybi07.hpp \
    websocketpp/processors/hybi08.hpp \
    websocketpp/processors/hybi13.hpp \
    websocketpp/processors/processor.hpp \
    websocketpp/random/none.hpp \
    websocketpp/random/random_device.hpp \
    websocketpp/roles/client_endpoint.hpp \
    websocketpp/roles/server_endpoint.hpp \
    websocketpp/server.hpp \
    websocketpp/sha1/sha1.hpp \
    websocketpp/transport/asio/base.hpp \
    websocketpp/transport/asio/connection.hpp \
    websocketpp/transport/asio/endpoint.hpp \
    websocketpp/transport/asio/security/base.hpp \
    websocketpp/transport/asio/security/none.hpp \
    websocketpp/transport/asio/security/tls.hpp \
    websocketpp/transport/base/connection.hpp \
    websocketpp/transport/base/endpoint.hpp \
    websocketpp/transport/debug/base.hpp \
    websocketpp/transport/debug/connection.hpp \
    websocketpp/transport/debug/endpoint.hpp \
    websocketpp/transport/iostream/base.hpp \
    websocketpp/transport/iostream/connection.hpp \
    websocketpp/transport/iostream/endpoint.hpp \
    websocketpp/transport/stub/base.hpp \
    websocketpp/transport/stub/connection.hpp \
    websocketpp/transport/stub/endpoint.hpp \
    websocketpp/uri.hpp \
    websocketpp/utf8_validator.hpp \
    websocketpp/utilities.hpp \
    websocketpp/version.hpp
